### ISSUE TITLE
duplo-bomber

### ISSUE THREAD

**Issue by NikitaFun** [batiscuff/duplo-bomber#3]
writes: "Wrong number of characters", tell me what to do

**Comment by batiscuff** [comment]
@NikitaFun fixed. Reinstall bomber

**Comment by Pupirchick** [comment]
Building wheels for collected packages: gevent
  Building wheel for gevent (PEP 517) 
Tell me what to do)

**Comment by batiscuff** [comment]
Lol, I don't know. This is not my problem, use linux, or install event for windows

**Comment by batiscuff** [comment]
> Building wheels for collected packages: gevent
> Building wheel for gevent (PEP 517)
> Tell me what to do)

Lol, I don't know. This is not my problem, use linux, or install event for windows
