### ISSUE TITLE
Ошибка при запуске не подскажите как устранить?

### ISSUE THREAD

**Issue by partizan007** [batiscuff/duplo-bomber#4]
Traceback (most recent call last):
  File "duplo_spam.py", line 4, in <module>
    from send_requests import send_requests
  File "/home/partizan/duplo-bomber/send_requests.py", line 8, in <module>
    import qrequests
ModuleNotFoundError: No module named 'qrequests'

**Comment by batiscuff** [comment]
> Traceback (most recent call last):
> File "duplo_spam.py", line 4, in
> from send_requests import send_requests
> File "/home/partizan/duplo-bomber/send_requests.py", line 8, in
> import qrequests
> ModuleNotFoundError: No module named 'qrequests'

`pip3 install -r requirements.txt`
