### ISSUE TITLE
Это фейк

### ISSUE THREAD

**Issue by AlekseevichIvan** [batiscuff/duplo-bomber#7]
Отстой! Репа фейковая? Да!
![Снимок экрана 2023-07-06 153252](https://github.com/batiscuff/duplo-bomber/assets/100844313/51735b34-573a-494b-a5f0-4de524baec3e)
т.е. без интернета работает, да-да.  
КАК? А очень просто, Нечего вестись на таких батискофов как скриптового ребёнка!

**Comment by batiscuff** [comment]
> Отстой! Репа фейковая? Да! ![Снимок экрана 2023-07-06 153252](https://user-images.githubusercontent.com/100844313/251454164-51735b34-573a-494b-a5f0-4de524baec3e.jpg) т.е. без интернета работает, да-да. КАК? А очень просто, Нечего вестись на таких батискофов как скриптового ребёнка!

Бро, ты ебанутый? Посмотри когда был написан этот бомбер и на календарь, потом снова посмотри когда он был написан и снова на календарь, может до тебя огузка дойдёт что ему лет больше чем тебе. Сервисы уже давно сменили свои способы регистрации аккаунтов, поэтому ни одна смс-ка не приходит, а пишет оно так в консоле потому что ебланы забыли отключить старые апи и запросы к ним ещё доходят.
